spring:
  application:
    name: testApp
    version: 1.0
  profiles:
    active: dev
    include: discovery-local

bestjoy:
  discovery:
    server-addr: http://192.168.116.128:8848
    service-name: testAppService
