spring:
  application:
    name: cloud-eureka-service
  profiles:
    active: dev

#eureka:
#  server:
#    eviction-interval-timer-in-ms: 3000 #启用主动失效，并且每次主动失效检测间隔为3s
#    response-cache-update-interval-ms: 3000 #刷新readCacheMap的时间
#    use-read-only-response-cache: false
#  instance:
#    lease-expiration-duration-in-seconds: 10
#    lease-renewal-interval-in-seconds: 10
#    prefer-ip-address: true
#  client:
#    registry-fetch-interval-seconds: 10
#    fetch-registry: true
#    register-with-eureka: true
#    transport:
#      applications-resolver-use-ip: true

##ribbon
#ribbon:
#  eager-load:
#    enabled: true
#  ConnectTimeout: 5000
#  ReadTimeout: 5000
#  MaxAutoRetries: 0
#  RetryableStatusCodes: 502
#  ServerListRefreshInterval: 3000

server:
  port: 8761 #启动端口
